import 'package:drift/drift.dart';
import '../database/app_database.dart';
import '../core/constants/exercise_constants.dart';

class ExerciseSeedData {
  ExerciseSeedData._();

  static List<ExercisesCompanion> get all => [
    // ─── CHEST ───
    _e('Push-Up', BodyPart.chest, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.push,
      desc: 'The fundamental upper-body push exercise. Builds chest, shoulders, and triceps using your own bodyweight.',
      instr: 'Place hands shoulder-width apart on the floor. Lower your chest until it nearly touches the ground, keeping elbows at 45°. Push back up explosively. Keep core braced and body in a straight line throughout.',
      sets: 3, reps: 12, tempo: '2-0-1-0'),
    _e('Wide Push-Up', BodyPart.chest, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.push,
      desc: 'A wider hand placement shifts emphasis to the outer chest and front deltoids, reducing tricep involvement.',
      instr: 'Place hands 1.5x shoulder width apart. Lower chest to the floor keeping elbows flared slightly. Push back up. Avoid sagging hips.',
      sets: 3, reps: 10, tempo: '2-1-1-0'),
    _e('Diamond Push-Up', BodyPart.chest, Equipment.bodyweightFloor, Difficulty.intermediate, MuscleAction.push,
      desc: 'Close-grip variation that heavily targets the triceps and inner chest. Harder than standard push-ups.',
      instr: 'Form a diamond shape with your index fingers and thumbs under your chest. Lower slowly until chest touches hands, then press up. Keep elbows close to your sides.',
      sets: 3, reps: 8, tempo: '3-1-1-0'),
    _e('Dumbbell Bench Press', BodyPart.chest, Equipment.dumbbells, Difficulty.beginner, MuscleAction.push,
      desc: 'A staple chest builder. Dumbbells allow greater range of motion and independent arm work compared to barbell.',
      instr: 'Lie flat on a bench with dumbbells at chest level, palms forward. Press up until arms are extended but not locked. Lower slowly to the sides of your chest, feeling a stretch at the bottom.',
      sets: 4, reps: 10, tempo: '3-1-2-1', secondaryEquipment: Equipment.bench),
    _e('Dumbbell Fly', BodyPart.chest, Equipment.dumbbells, Difficulty.intermediate, MuscleAction.isolation,
      desc: 'An isolation movement that stretches and contracts the chest through a wide arc. Great for chest definition.',
      instr: 'Lie on a bench holding dumbbells above chest with a slight elbow bend. Open arms in a wide arc until you feel a deep chest stretch. Squeeze chest to bring dumbbells back together. Maintain the slight bend throughout.',
      sets: 3, reps: 12, tempo: '3-1-2-1', secondaryEquipment: Equipment.bench),
    _e('Barbell Bench Press', BodyPart.chest, Equipment.straightBarbell, Difficulty.intermediate, MuscleAction.push,
      desc: 'The king of chest exercises. A heavy compound movement that builds overall upper body pressing strength.',
      instr: 'Lie on bench, grip bar slightly wider than shoulders. Unrack and lower the bar to mid-chest with control. Press up forcefully to lockout. Keep shoulder blades retracted and feet flat on the floor.',
      sets: 4, reps: 8, tempo: '3-1-2-1', secondaryEquipment: Equipment.bench),
    _e('Cable Crossover', BodyPart.chest, Equipment.cablesMachine, Difficulty.intermediate, MuscleAction.isolation,
      desc: 'A cable fly variation providing constant tension throughout the movement. Excellent for chest shaping and the squeeze at peak contraction.',
      instr: 'Stand between cable stacks with pulleys set high. Step forward slightly. With a slight elbow bend, bring handles together in front of your chest in a hugging motion. Squeeze hard at the bottom, then control the return.',
      sets: 3, reps: 12, tempo: '2-1-2-1'),

    // ─── BACK ───
    _e('Superman', BodyPart.back, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.pull,
      desc: 'A bodyweight lower back and posterior chain exercise. Strengthens the erector spinae muscles that support your spine.',
      instr: 'Lie face down with arms extended overhead. Simultaneously raise arms, chest, and legs off the floor. Hold the top position briefly, squeezing your lower back and glutes. Lower with control.',
      sets: 3, reps: 12, tempo: '1-2-1-0'),
    _e('Pull-Up', BodyPart.back, Equipment.pullUpBar, Difficulty.intermediate, MuscleAction.pull,
      desc: 'The ultimate upper back exercise. Builds wide lats, strong biceps, and grip strength with just your bodyweight.',
      instr: 'Hang from a bar with overhand grip, slightly wider than shoulders. Pull yourself up until chin clears the bar, leading with your chest. Lower slowly to a full hang. Avoid kipping or swinging.',
      sets: 3, reps: 6, tempo: '2-1-3-1'),
    _e('Dumbbell Row', BodyPart.back, Equipment.dumbbells, Difficulty.beginner, MuscleAction.pull,
      desc: 'A unilateral rowing movement for the lats, rhomboids, and mid-back. Helps fix strength imbalances between sides.',
      instr: 'Place one hand and knee on a bench for support. Row the dumbbell to your hip, driving the elbow back and squeezing your shoulder blade. Lower with a controlled stretch. Keep torso parallel to the floor.',
      sets: 3, reps: 10, tempo: '2-1-2-1', secondaryEquipment: Equipment.bench),
    _e('Barbell Bent-Over Row', BodyPart.back, Equipment.straightBarbell, Difficulty.intermediate, MuscleAction.compound,
      desc: 'A heavy compound back builder. Targets the entire back from lats to traps to erectors.',
      instr: 'Hinge at hips with knees slightly bent, torso at ~45°. Grip barbell just outside knees. Row the bar to your lower chest, squeezing shoulder blades together. Lower under control. Keep back flat throughout.',
      sets: 4, reps: 8, tempo: '2-1-3-1'),
    _e('Resistance Band Lat Pulldown', BodyPart.back, Equipment.resistanceBands, Difficulty.beginner, MuscleAction.pull,
      desc: 'A band-based lat pulldown you can do anywhere. Great for beginners building back width at home.',
      instr: 'Anchor band above head height. Kneel or stand and grip both ends. Pull down to upper chest, squeezing lats. Slowly return to the stretched position. Keep chest up and avoid leaning back too far.',
      sets: 3, reps: 12, tempo: '2-1-3-0'),

    // ─── SHOULDERS ───
    _e('Pike Push-Up', BodyPart.shoulders, Equipment.bodyweightFloor, Difficulty.intermediate, MuscleAction.push,
      desc: 'A bodyweight overhead pressing movement. The inverted body angle shifts load to the shoulders instead of chest.',
      instr: 'Start in a downward dog position — hips high, hands shoulder-width apart. Bend elbows to lower your head toward the floor between your hands. Push back up. The steeper the angle, the harder it is.',
      sets: 3, reps: 8, tempo: '2-1-2-0'),
    _e('Dumbbell Lateral Raise', BodyPart.shoulders, Equipment.dumbbells, Difficulty.beginner, MuscleAction.isolation,
      desc: 'The go-to isolation exercise for the side (lateral) deltoids. Builds shoulder width and the "capped" look.',
      instr: 'Stand holding dumbbells at your sides. Raise arms out to the sides until parallel to the floor, leading with elbows. Pause briefly, then lower slowly. Use a weight you can control — no swinging.',
      sets: 3, reps: 12, tempo: '2-1-3-0'),
    _e('Dumbbell Overhead Press', BodyPart.shoulders, Equipment.dumbbells, Difficulty.beginner, MuscleAction.push,
      desc: 'A versatile pressing movement for all three heads of the deltoid plus the triceps. Can be done seated or standing.',
      instr: 'Sit or stand with dumbbells at shoulder height, palms forward. Press straight overhead until arms are fully extended. Lower back to shoulders with control. Keep core tight to avoid arching your back.',
      sets: 3, reps: 10, tempo: '2-1-2-1'),
    _e('Barbell Overhead Press', BodyPart.shoulders, Equipment.straightBarbell, Difficulty.intermediate, MuscleAction.push,
      desc: 'The classic standing overhead press. A true test of upper body strength that works shoulders, traps, and core stability.',
      instr: 'Grip barbell at shoulder width, resting on front delts. Brace core and press straight up overhead. Lock out at the top, then lower to chin level. Avoid excessive back lean — keep it strict.',
      sets: 4, reps: 6, tempo: '3-1-2-1'),
    _e('Dumbbell Front Raise', BodyPart.shoulders, Equipment.dumbbells, Difficulty.beginner, MuscleAction.isolation,
      desc: 'Targets the front (anterior) deltoid. A simple isolation movement for shoulder development.',
      instr: 'Stand with dumbbells in front of your thighs, palms facing you. Raise one or both arms to shoulder height keeping a slight elbow bend. Lower slowly. Alternate arms or do both together.',
      sets: 3, reps: 12, tempo: '2-0-3-0'),
    _e('Face Pull', BodyPart.shoulders, Equipment.resistanceBands, Difficulty.beginner, MuscleAction.pull,
      desc: 'Targets the rear deltoids and rotator cuff. Essential for shoulder health and posture, especially for desk workers.',
      instr: 'Anchor band at face height. Grip ends with palms down. Pull toward your face, spreading hands apart and squeezing rear delts. Elbows should stay high. Slowly return. Focus on the squeeze, not the weight.',
      sets: 3, reps: 15, tempo: '1-2-2-0'),

    // ─── BICEPS ───
    _e('Dumbbell Curl', BodyPart.biceps, Equipment.dumbbells, Difficulty.beginner, MuscleAction.isolation,
      desc: 'The classic bicep builder. Simple, effective, and allows supination for maximum bicep activation.',
      instr: 'Stand holding dumbbells at your sides, palms forward. Curl both dumbbells to your shoulders by flexing the biceps. Squeeze at the top, then lower slowly. Keep upper arms pinned to your sides — no swinging.',
      sets: 3, reps: 12, tempo: '2-1-3-0'),
    _e('Barbell Curl', BodyPart.biceps, Equipment.straightBarbell, Difficulty.beginner, MuscleAction.isolation,
      desc: 'Allows heavier loads than dumbbells for maximum bicep overload. The straight bar forces both arms to work together.',
      instr: 'Stand holding a barbell with underhand grip at hip width. Curl the bar to shoulder height keeping elbows stationary. Squeeze biceps hard, then lower under control. Stand tall — no leaning back.',
      sets: 3, reps: 10, tempo: '2-1-3-0'),
    _e('Hammer Curl', BodyPart.biceps, Equipment.dumbbells, Difficulty.beginner, MuscleAction.isolation,
      desc: 'The neutral grip targets the brachialis and brachioradialis, building thickness in the arms and forearm size.',
      instr: 'Stand with dumbbells at sides, palms facing each other (neutral grip). Curl up keeping palms facing in throughout. Squeeze at top, lower with control. Works the "outer" arm more than standard curls.',
      sets: 3, reps: 12, tempo: '2-0-3-0'),
    _e('EZ Bar Curl', BodyPart.biceps, Equipment.ezCurlBar, Difficulty.beginner, MuscleAction.isolation,
      desc: 'The angled grip is easier on the wrists than a straight bar while still allowing heavy bicep loading.',
      instr: 'Grip the EZ bar at the angled portions with underhand grip. Curl to shoulders keeping elbows fixed at your sides. Lower slowly, resisting gravity. Full extension at the bottom.',
      sets: 3, reps: 10, tempo: '2-1-3-1'),
    _e('Resistance Band Curl', BodyPart.biceps, Equipment.resistanceBands, Difficulty.beginner, MuscleAction.isolation,
      desc: 'Band curls provide increasing resistance at the top where biceps are strongest. Great for home training and burnouts.',
      instr: 'Stand on the middle of the band, grip both ends. Curl hands to shoulders against band tension. Squeeze at top, lower with control. The band gets harder as you curl higher.',
      sets: 3, reps: 15, tempo: '2-0-2-0'),

    // ─── TRICEPS ───
    _e('Chair Dips', BodyPart.triceps, Equipment.chair, Difficulty.beginner, MuscleAction.push,
      desc: 'An accessible bodyweight exercise for triceps using any sturdy chair or bench. Great for beginners.',
      instr: 'Sit on the edge of a chair, hands gripping the edge. Slide your hips off, legs extended. Lower your body by bending elbows to ~90°. Push back up by straightening arms. Keep back close to the chair.',
      sets: 3, reps: 10, tempo: '3-0-2-0'),
    _e('Dumbbell Kickback', BodyPart.triceps, Equipment.dumbbells, Difficulty.beginner, MuscleAction.isolation,
      desc: 'Isolates the tricep with a peak contraction at full arm extension. Effective with light to moderate weight.',
      instr: 'Hinge forward at the hips with one arm supported. Hold the dumbbell with upper arm parallel to the floor. Extend the forearm back until your arm is straight. Squeeze the tricep, then lower slowly.',
      sets: 3, reps: 12, tempo: '1-1-3-0'),
    _e('Overhead Tricep Extension', BodyPart.triceps, Equipment.dumbbells, Difficulty.beginner, MuscleAction.isolation,
      desc: 'Stretches the long head of the tricep under load, promoting full development. Can use one dumbbell with both hands.',
      instr: 'Hold one dumbbell overhead with both hands, arms extended. Lower the weight behind your head by bending elbows. Keep upper arms close to your ears. Extend back to the top and squeeze.',
      sets: 3, reps: 10, tempo: '3-1-2-0'),
    _e('Skull Crusher', BodyPart.triceps, Equipment.ezCurlBar, Difficulty.intermediate, MuscleAction.isolation,
      desc: 'A lying tricep extension that provides a deep stretch under load. Named for the bar path — don\'t actually crush your skull.',
      instr: 'Lie on a bench with an EZ bar extended above your chest. Bend only at the elbows to lower the bar toward your forehead. Stop just above, then extend back up. Keep upper arms vertical throughout.',
      sets: 3, reps: 10, tempo: '3-1-2-0', secondaryEquipment: Equipment.bench),
    _e('Dip Station Dips', BodyPart.triceps, Equipment.dipStation, Difficulty.intermediate, MuscleAction.push,
      desc: 'An advanced bodyweight push exercise that loads the triceps and chest heavily. A true upper body strength builder.',
      instr: 'Support yourself on parallel bars with arms locked. Lower your body by bending elbows until upper arms are parallel to the floor. Push back up to lockout. Lean slightly forward for more chest, stay upright for more triceps.',
      sets: 3, reps: 8, tempo: '3-1-2-1'),

    // ─── ABS / CORE ───
    _e('Plank', BodyPart.absCore, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.isometric,
      desc: 'The foundational core stability exercise. Trains the entire core to resist extension under load — no movement needed.',
      instr: 'Rest on forearms and toes, body forming a straight line from head to heels. Squeeze your abs, glutes, and quads. Breathe steadily. Don\'t let your hips sag or pike up. Hold for the prescribed duration.',
      sets: 3, reps: 1, duration: 30, tempo: '0-0-0-0'),
    _e('Crunch', BodyPart.absCore, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.isolation,
      desc: 'The basic abdominal flexion exercise. Targets the rectus abdominis (the "six-pack" muscle).',
      instr: 'Lie on your back with knees bent, hands behind your head. Curl your shoulders off the ground by contracting your abs — don\'t pull on your neck. Squeeze at the top, then lower slowly. Small range of motion is fine.',
      sets: 3, reps: 15, tempo: '2-1-1-0'),
    _e('Leg Raise', BodyPart.absCore, Equipment.bodyweightFloor, Difficulty.intermediate, MuscleAction.isolation,
      desc: 'Targets the lower portion of the abs through hip flexion. Harder than it looks when done with control.',
      instr: 'Lie flat on your back, hands at your sides or under your hips. Raise straight legs to 90° while pressing your lower back into the floor. Lower legs slowly without letting them touch the floor. The slower, the better.',
      sets: 3, reps: 12, tempo: '2-0-4-0'),
    _e('Mountain Climber', BodyPart.absCore, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.cardio,
      desc: 'A dynamic plank variation that adds cardio conditioning. Works the core, hip flexors, and shoulders simultaneously.',
      instr: 'Start in push-up position. Rapidly alternate driving knees toward your chest. Keep hips low and core tight. Move as fast as you can while maintaining good form. Breathe rhythmically.',
      sets: 3, reps: 20, tempo: '0-0-0-0'),
    _e('Russian Twist', BodyPart.absCore, Equipment.bodyweightFloor, Difficulty.intermediate, MuscleAction.isolation,
      desc: 'A rotational core exercise that targets the obliques. Can be done with or without weight for added difficulty.',
      instr: 'Sit with knees bent and feet slightly off the floor. Lean back to ~45°. Rotate your torso side to side, touching the floor beside each hip. Keep your chest up and move from the core, not just the arms.',
      sets: 3, reps: 16, tempo: '1-0-1-0'),
    _e('Dead Bug', BodyPart.absCore, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.isometric,
      desc: 'An anti-extension core exercise that teaches proper bracing. Excellent for lower back health and core coordination.',
      instr: 'Lie on your back with arms pointing to the ceiling and knees bent at 90°. Slowly extend one arm overhead and the opposite leg out straight, keeping your lower back pressed flat. Return and switch sides.',
      sets: 3, reps: 10, tempo: '3-1-3-0'),
    _e('Ab Wheel Rollout', BodyPart.absCore, Equipment.abWheel, Difficulty.advanced, MuscleAction.compound,
      desc: 'One of the most challenging core exercises. Trains anti-extension under extreme leverage, building bulletproof abs.',
      instr: 'Kneel with the ab wheel on the floor in front of you. Roll forward as far as you can while keeping your core braced and back flat. Pull the wheel back using your abs — don\'t collapse at the hips.',
      sets: 3, reps: 8, tempo: '3-1-3-0'),

    // ─── GLUTES ───
    _e('Glute Bridge', BodyPart.glutes, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.isolation,
      desc: 'The best bodyweight exercise for glute activation. Builds the foundation for stronger hips and a healthy lower back.',
      instr: 'Lie on your back with knees bent and feet flat. Drive through your heels to raise your hips until your body forms a straight line from knees to shoulders. Squeeze glutes hard at the top. Lower slowly.',
      sets: 3, reps: 15, tempo: '2-2-1-0'),
    _e('Hip Thrust', BodyPart.glutes, Equipment.bench, Difficulty.intermediate, MuscleAction.compound,
      desc: 'The number one glute-building exercise. Allows heavy loading in the hip extension pattern for maximum growth.',
      instr: 'Sit on the floor with upper back against a bench. Roll a barbell over your hips (use a pad). Drive hips up until thighs are parallel to the floor. Squeeze glutes at the top for 1 second. Lower with control.',
      sets: 3, reps: 10, tempo: '2-2-2-1', secondaryEquipment: Equipment.straightBarbell),
    _e('Donkey Kick', BodyPart.glutes, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.isolation,
      desc: 'A simple bodyweight glute isolation performed on all fours. Good for muscle activation and mind-muscle connection.',
      instr: 'Get on hands and knees. Keeping the knee bent at 90°, drive one foot toward the ceiling. Squeeze the glute at the top. Lower slowly without resting the knee. Complete all reps on one side, then switch.',
      sets: 3, reps: 12, tempo: '1-1-2-0'),
    _e('Bulgarian Split Squat', BodyPart.glutes, Equipment.bodyweightFloor, Difficulty.intermediate, MuscleAction.compound,
      desc: 'A single-leg exercise that crushes the glutes and quads while building balance. Surprisingly intense with just bodyweight.',
      instr: 'Stand in a lunge stance with your rear foot elevated on a bench or chair behind you. Lower straight down until your front thigh is parallel to the floor. Drive up through the front heel. Keep torso upright.',
      sets: 3, reps: 10, tempo: '3-1-2-0', secondaryEquipment: Equipment.chair),

    // ─── QUADS ───
    _e('Bodyweight Squat', BodyPart.quads, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.compound,
      desc: 'The fundamental lower body movement pattern. Builds quads, glutes, and mobility. Master this before adding weight.',
      instr: 'Stand with feet shoulder-width apart, toes slightly out. Sit back and down as if sitting into a chair. Go as deep as your mobility allows (aim for thighs parallel). Drive up through your heels.',
      sets: 3, reps: 15, tempo: '3-1-2-0'),
    _e('Goblet Squat', BodyPart.quads, Equipment.dumbbells, Difficulty.beginner, MuscleAction.compound,
      desc: 'A front-loaded squat that naturally teaches good squatting mechanics. The counterbalance helps you squat deeper.',
      instr: 'Hold a dumbbell vertically at chest height, close to your body. Squat down between your knees, keeping chest tall. Push elbows against inner knees to open up the hips. Drive up through heels.',
      sets: 3, reps: 12, tempo: '3-1-2-1'),
    _e('Lunge', BodyPart.quads, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.compound,
      desc: 'A unilateral leg exercise that builds strength, balance, and coordination. Works quads, glutes, and stabilizers.',
      instr: 'Step forward into a long stride. Lower until both knees are at approximately 90°. The rear knee should nearly touch the floor. Push off the front foot to return to standing. Alternate legs.',
      sets: 3, reps: 12, tempo: '2-0-2-0'),
    _e('Wall Sit', BodyPart.quads, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.isometric,
      desc: 'An isometric quad hold that builds muscular endurance and mental toughness. Burns like nothing else.',
      instr: 'Lean your back flat against a wall. Slide down until your thighs are parallel to the floor, knees at 90°. Hold this position. Press your lower back into the wall. Breathe steadily through the burn.',
      sets: 3, reps: 1, duration: 30, tempo: '0-0-0-0'),
    _e('Barbell Back Squat', BodyPart.quads, Equipment.straightBarbell, Difficulty.intermediate, MuscleAction.compound,
      desc: 'The king of all exercises. Builds total lower body strength and stimulates full-body muscle growth like nothing else.',
      instr: 'Position the bar on your upper traps. Unrack and step back. Squat down by pushing your hips back and bending your knees. Descend to parallel or below. Drive up powerfully. Keep chest up and core braced.',
      sets: 4, reps: 8, tempo: '3-1-2-1'),
    _e('Leg Press', BodyPart.quads, Equipment.legPressMachine, Difficulty.beginner, MuscleAction.compound,
      desc: 'A machine exercise that lets you load the legs heavy with less technique required than free squats.',
      instr: 'Sit in the leg press with feet shoulder-width on the platform. Release the safeties and lower the platform by bending your knees to ~90°. Press up without fully locking out. Keep lower back pressed into the seat.',
      sets: 3, reps: 12, tempo: '3-1-2-0'),

    // ─── HAMSTRINGS ───
    _e('Romanian Deadlift', BodyPart.hamstrings, Equipment.dumbbells, Difficulty.intermediate, MuscleAction.compound,
      desc: 'A hip hinge that stretches and strengthens the hamstrings and glutes under load. Essential for posterior chain development.',
      instr: 'Stand holding dumbbells in front of your thighs. Hinge at the hips, pushing your butt back. Lower the weights along your legs while keeping a slight knee bend. Feel the hamstring stretch. Stand up by driving hips forward.',
      sets: 3, reps: 10, tempo: '4-1-2-1'),
    _e('Good Morning', BodyPart.hamstrings, Equipment.straightBarbell, Difficulty.intermediate, MuscleAction.compound,
      desc: 'A barbell hip hinge that builds the posterior chain. Named because the movement resembles bowing in greeting.',
      instr: 'Bar on upper back, feet hip-width. Hinge at the hips, pushing your butt back while keeping your back flat. Lower until your torso is roughly parallel to the floor. Stand up by driving the hips. Go light until you master the form.',
      sets: 3, reps: 10, tempo: '3-1-2-1'),
    _e('Nordic Curl', BodyPart.hamstrings, Equipment.bodyweightFloor, Difficulty.advanced, MuscleAction.isolation,
      desc: 'The most effective bodyweight hamstring exercise. Builds extreme eccentric strength and prevents hamstring injuries.',
      instr: 'Kneel on a pad with your feet anchored (under a heavy object or by a partner). Slowly lower your body forward in a controlled fall, resisting with your hamstrings. Use your hands to catch yourself, then curl back up.',
      sets: 3, reps: 5, tempo: '5-0-1-0'),

    // ─── CALVES ───
    _e('Standing Calf Raise', BodyPart.calves, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.isolation,
      desc: 'Targets the gastrocnemius (the larger, visible calf muscle). Performed standing to fully engage the muscle.',
      instr: 'Stand on the edge of a step with heels hanging off. Rise up on your toes as high as possible, squeezing your calves. Pause at the top. Lower slowly below the step level for a full stretch. Full range of motion is key.',
      sets: 3, reps: 15, tempo: '2-2-3-0'),
    _e('Seated Calf Raise', BodyPart.calves, Equipment.dumbbells, Difficulty.beginner, MuscleAction.isolation,
      desc: 'Targets the soleus (the deeper calf muscle) which is worked best with bent knees. Complements standing calf raises.',
      instr: 'Sit on a chair or bench with dumbbells resting on your knees. Place the balls of your feet on a step or plate. Raise your heels as high as possible. Pause and squeeze, then lower slowly for a deep stretch.',
      sets: 3, reps: 15, tempo: '2-2-3-0', secondaryEquipment: Equipment.chair),

    // ─── FULL BODY / CARDIO ───
    _e('Jumping Jacks', BodyPart.fullBody, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.cardio,
      desc: 'A classic warm-up and cardio exercise. Simple but effective for raising heart rate and warming up the whole body.',
      instr: 'Stand with feet together and arms at your sides. Jump your feet apart while simultaneously raising arms overhead. Jump back to the starting position. Keep a steady rhythm and land softly on the balls of your feet.',
      sets: 3, reps: 30, tempo: '0-0-0-0'),
    _e('Burpees', BodyPart.fullBody, Equipment.bodyweightFloor, Difficulty.intermediate, MuscleAction.cardio,
      desc: 'The ultimate full-body conditioning exercise. Combines a squat, plank, push-up, and jump into one brutal movement.',
      instr: 'From standing, squat down and place hands on the floor. Kick feet back into a push-up position. Do a push-up (optional for beginners). Jump feet back to your hands. Explode up into a jump with arms overhead.',
      sets: 3, reps: 10, tempo: '0-0-0-0'),
    _e('High Knees', BodyPart.fullBody, Equipment.bodyweightFloor, Difficulty.beginner, MuscleAction.cardio,
      desc: 'Running in place with exaggerated knee lift. A high-intensity cardio exercise that builds hip flexor endurance.',
      instr: 'Run in place, driving your knees up to hip height with each step. Pump your arms in sync. Stay on the balls of your feet. Keep your core engaged and torso upright. Go as fast as you can maintain.',
      sets: 3, reps: 30, tempo: '0-0-0-0'),
    _e('Kettlebell Swing', BodyPart.fullBody, Equipment.kettlebells, Difficulty.intermediate, MuscleAction.compound,
      desc: 'An explosive hip hinge that builds power, conditioning, and posterior chain strength. The foundation of kettlebell training.',
      instr: 'Stand with feet wider than shoulders, kettlebell on the floor ahead of you. Hike the bell between your legs, then snap your hips forward to swing it to chest height. Let it fall back and hinge again. Power comes from the hips, not the arms.',
      sets: 3, reps: 15, tempo: '1-0-1-0'),
  ];

  static ExercisesCompanion _e(
    String name,
    BodyPart bodyPart,
    Equipment equipment,
    Difficulty difficulty,
    MuscleAction action, {
    String desc = '',
    String instr = '',
    int sets = 3,
    int reps = 10,
    int? duration,
    String tempo = '2-1-1-0',
    Equipment? secondaryEquipment,
  }) {
    return ExercisesCompanion.insert(
      name: name,
      description: Value(desc),
      instructions: Value(instr),
      bodyPartIndex: bodyPart.index,
      equipmentIndex: equipment.index,
      difficultyIndex: difficulty.index,
      muscleActionIndex: action.index,
      defaultSets: Value(sets),
      defaultReps: Value(reps),
      defaultDurationSecs: Value(duration),
      defaultTempo: Value(tempo),
      secondaryEquipmentIndex: Value(secondaryEquipment?.index),
    );
  }
}
